CREATE TABLE BORROWER(
    CUSTOMER_NAME VARCHAR(20),
    FOREIGN KEY(CUSTOMER_NAME) REFERENCES DEPOSITOR(CUSTOMER_NAME),
    LOAN_NUMBER NUMBER(10),
    FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER)
);


INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'John Doe',
    1001
);

INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'Jane Doe',
    2002
);

INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'Peter Parker',
    3003
);

INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'Mary Jane Watson',
    4004
);

INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'Bruce Wayne',
    5005
);

INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'Clark Kent',
    6006
);

INSERT INTO BORROWER (
    CUSTOMER_NAME,
    LOAN_NUMBER
) VALUES (
    'Diana Prince',
    7007
);