CREATE TABLE DEPOSITOR(
    CUSTOMER_NAME VARCHAR(20) PRIMARY KEY,
    ACCOUNT_NUMBER NUMBER(20),
    FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'John Doe',
    1234567890
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Jane Doe',
    9876543210
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Peter Parker',
    0987654321
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Mary Jane Watson',
    1987654320
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Bruce Wayne',
    2987654319
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Clark Kent',
    3987654318
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Diana Prince',
    4987654317
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Arthur Curry',
    5987654316
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Victor Stone',
    6987654315
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Barry Allen',
    7987654314
);

INSERT INTO DEPOSITOR (
    CUSTOMER_NAME,
    ACCOUNT_NUMBER
) VALUES (
    'Hal Jordan',
    8987654313
);